# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6016372fb28b4189696115faf3df6acbf4eb9b8e85c78e2d5aecf2d890a30c36e3797d1b567de9ac3ca505219be99662503cbb3129a8e9437b2a0950dcf39ae

test:
  secret_key_base: 7b83771d1ccb6e692ababf96eccb47e496e93dc4502eaca39c08919b8828336f81101b7548699a806455646aaa5c8502ce128d975d435faddad7ff985cb940cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
